id: PBF523F3B
initial_creation_type: input
source_metadata:
  title: Minyak Kunzang Sönam Series
  language: en
  description: 'Texts by and about Minyak Kunzang Sönam (mi nyag kun bzang bsod nams,
    1823–1905) alias Thubten Chökyi Drakpa (thub bstan chos kyi grags pa) :'
  volume:
    c9a90c619a9f4c0ba088308a16e4698b:
      title: Overview of the Bodhicaryāvatāra
      parent: Bodhicaryāvatāra
created_at: '2022-03-01T00:49:12.157135'
last_modified_at: '2022-03-01T00:49:12.157142'
